export default {
  LOAD_SEQUENCES_REQUEST: 'LOAD_SEQUENCES_REQUEST',
  LOAD_SEQUENCES_SUCCESS: 'LOAD_SEQUENCES_SUCCESS',
  LOAD_SEQUENCES_FAILURE: 'LOAD_SEQUENCES_FAILURE',
  CREATE_SEQUENCE_REQUEST: 'CREATE_SEQUENCE_REQUEST',
  CREATE_SEQUENCE_SUCCESS: 'CREATE_SEQUENCE_SUCCESS',
  CREATE_SEQUENCE_FAILURE: 'CREATE_SEQUENCE_FAILURE',
  DELETE_SEQUENCE_REQUEST: 'DELETE_SEQUENCE_REQUEST',
  DELETE_SEQUENCE_SUCCESS: 'DELETE_SEQUENCE_SUCCESS',
  DELETE_SEQUENCE_FAILURE: 'DELETE_SEQUENCE_FAILURE',
  RESET_SEQUENCE_REQUEST: 'RESET_SEQUENCE_REQUEST',
  RESET_SEQUENCE_SUCCESS: 'RESET_SEQUENCE_SUCCESS',
  RESET_SEQUENCE_FAILURE: 'RESET_SEQUENCE_FAILURE',
}
